### ISSUE TITLE
How i can fix "Unable to open video device"

### ISSUE THREAD

**Issue by UrbanSide** [ccrisan/motioneye#1885] opened 2020-08-15 14:23 UTC
![image](https://user-images.githubusercontent.com/26259129/90314352-d2aebf00-df1b-11ea-88d5-8cb3cbde4814.png)
I have this error,on Orange Pi lite, with 

```
motionEye Version | 0.42.1
Motion Version | 4.0
OS Version | Ubuntu 18.04
```
My cam translate on rtsp://admin:123456@192.168.1.10:554/mode=real&idc=1&ids=1 and i use it on cam settings in MotionEye

**Comment by starbasessd** [comment] 2020-11-04 20:46
I would update/upgrade motion & motionEye, if you haven't already.
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed by starbasessd** 2020-11-04 20:46 UTC

**Comment by Kras-s-savchiK** [comment] 2021-02-13 13:30
Can you fix this issue?

**Comment by starbasessd** [comment] 2021-02-13 14:06
Please open a new issue.
Include the following information:
Which SBC?
What base OS?
Which version of motion?
Which version of motionEye?
Which install instructions were followed?
What camera used?
How are your SBC and camera connected?
