### ISSUE TITLE
motioneye.conf log_level property not working

### ISSUE THREAD

**Issue by mcgyver83** [ccrisan/motioneye#1264] opened 2019-05-07 08:39 UTC
I'm running motioneye using docker on a raspberry pi2B using ccrisan/motioneye:0.40-armhf

I tried to set
`log_level warning`
but I still see a lot of 
`DEBUG: connection closed for mjpg client for camera 3 on port 9003` in the container log

**Comment by ccrisan** [comment] 2019-05-08 07:00
Duplicate of #1266

**Closed** 2019-05-08 07:06 UTC
Labels: duplicate
