### ISSUE TITLE
Downloaded videos from Firefox are converted from .mp4 to .mp4.mpeg

### ISSUE THREAD

**Issue by seb49** [ccrisan/motioneye#775] opened 2018-01-25 09:02 UTC
Hello,

I have an issue with Firefox. Downloaded videos from Firefox are converted from .mp4 to .mp4.mpeg I use VLC to view them but in this situation video show only the first image.

Regards

**Comment by Mrnt** [comment] 2018-01-29 02:52
@seb49 if you rename them back to xyz.mp4 by deleting the 'mpeg' suffix do they work? 
I suspect the problem is that all video is downloaded with mime type 'video/mpeg' regardless of actual type resulting in Firefox appending '.mpeg' which in turn is confusing VLC.

**Comment by ccrisan** [comment] 2018-02-05 12:21
Fixed via #785.

**Closed by ccrisan** 2018-02-05 12:21 UTC
