### ISSUE TITLE
ccrisan/motioneye:master-armhf constantly restarting ....

### ISSUE THREAD

**Issue by juergenschubert** [ccrisan/motioneye#1888] opened 2020-08-16 11:19 UTC
pi@raspberrypi:~/IOTstack $ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                           PORTS                    NAMES
7a63d787e64a        fa3bc6f20464                     "/bin/sh -c 'for add…"   10 minutes ago      Exited (139) 9 minutes ago                                lucid_fermat
227453edac28        fa3bc6f20464                     "/bin/sh -c 'for add…"   11 minutes ago      Exited (139) 11 minutes ago                               confident_mirzakhani
c2c248eac3af        ccrisan/motioneye:master-armhf   "/bin/sh -c 'test -e…"   25 minutes ago      Restarting (139) 2 seconds ago                            motioneye
550095c5259d        portainer/portainer              "/portainer"             25 minutes ago      Up 3 minutes                     0.0.0.0:9000->9000/tcp   portainer
pi@raspberrypi:~/IOTstack $

**Comment by starbasessd** [comment] 2020-11-04 20:43
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed by starbasessd** 2020-11-04 20:43 UTC
