### ISSUE TITLE
Cannot add network camera

### ISSUE THREAD

**Issue by PingPongLee** [ccrisan/motioneye#1890] opened 2020-08-18 15:15 UTC
I run this on my Synology in Docker, and i cannot add any camera to it. It just attempts to load the stream forever. I have a Raspberry Pi on the same network with MotionEye too, where there is no problems adding the same camera.

**Comment by starbasessd** [comment] 2020-11-04 20:41
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed by starbasessd** 2020-11-04 20:41 UTC
