### ISSUE TITLE
Unable to open video device / rtsp

### ISSUE THREAD

**Issue by Dobi29** [ccrisan/motioneye#109] opened 2016-01-23 09:57 UTC
Hello,
i have installed motioneye 0.30. My picam works fine. Now i want to add a network camera.
![unbenannt](https://cloud.githubusercontent.com/assets/16850445/12529642/41c301dc-c1bf-11e5-9dd0-2906b27e282b.JPG)
..but i get no stream...
![unbenannt2](https://cloud.githubusercontent.com/assets/16850445/12529649/ace8b290-c1bf-11e5-90f6-456086774273.JPG)
Using VLC with rtsp://192.168.178.26 i get the stream of the camera.
Thanks for your help.

**Comment by ektus** [comment] 2016-01-23 11:52
Do you have motion-mrdave installed? What's in the logfiles? Does the camera require authentication? 

Also, in my experience with motioneye rtsp does need a full path (including port number) to the stream, not merely the device IP address. For my QCam this reads "rtsp://192.168.0.12:554/h264Preview_01_sub"

Regards
Ektus.

**Comment by Dobi29** [comment] 2016-01-24 08:30
..thx for the reply. I try it with full path and authentication. The same. Now i want to install motion-mrdave for raspbian  --> https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian. 

note 2: A prebuilt version of Mr Dave's motion for Raspbian can be downloaded from here. Just download it and copy it to /usr/local/bin/motion

i cant' find the directory "motion"   and there is no solution in "google"....

How can install mrdave under respbian ? 

Regards Klaus

**Comment by ccrisan** [comment] 2016-01-24 08:34
There's no motion folder and there shouldn't be one. Copy your motion-mrdave binary to /usr/local/bin and rename it to motion (or shorter, copy it to /usr/local/bin/motion).

**Comment by Dobi29** [comment] 2016-01-24 08:43
Thx. Then restart the pi or going to step 3 ? How can i check using mrdave ?

**Comment by Dobi29** [comment] 2016-01-25 18:09
that's my log-File. My Cam : SN-IPC 5033SW-WI-EU

[0] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motioneye/motion.conf
[0] [NTC] [ALL] config_thread: Processing config file thread-1.conf
[0] [NTC] [ALL] config_thread: Processing config file thread-2.conf
[0] [ALR] [ALL] conf_cmdparse: Unknown config option "rtsp_uses_tcp"
[0] [NTC] [ALL] motion_startup: Motion 3.2.12+git20140228 Started
[0] [NTC] [ALL] motion_startup: Logging to syslog
[0] [NTC] [ALL] motion_startup: Using default log type (ALL)
[0] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
[2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31/)
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[2] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31/)
[2] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
[2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31/)
[2] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31/)
[2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31/)
[2] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31/)
[2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31/)
[2] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31/)
[2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31/)
[2] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31/)

**Comment by ektus** [comment] 2016-01-25 19:29
That camera should be from Sinocam, and according to 
https://www.ispyconnect.com/man.aspx?n=Sinocam I'd try and set the address in motion to rtsp://190.168.178.31:554//ucast/11 or maybe rtsp://190.168.178.31:554//11

You may also want to check if vlc shows a complete path.

**Comment by Dobi29** [comment] 2016-01-25 19:50
i was on this side yesterday and tried all adresses...i don't konw if have installed mrdave correct. how can i check this ?
[0] [ALR] [ALL] conf_cmdparse: Unknown config option "rtsp_uses_tcp"
[0] [NTC] [ALL] motion_startup: Motion 3.2.12+git20140228 Started
i copied mrdave into  /usr/local/bin. thats all ?

**Comment by ektus** [comment] 2016-01-25 19:59
I don't have access to my RPi during the week, so can't answer properly. But normally copying the binary is enough, and the version string doesn't look too wrong either, at least some date in 2014 could be correct. As a last resort, you could try and compile yourself, but first I'd try and investigate which complete url leads to the desired stream. In case the camera is ONVIF capable, you could try the ONVIF Device Manager to view it's properties. http://sourceforge.net/projects/onvifdm/

**Comment by Dobi29** [comment] 2016-01-25 20:32
![unbenannt4](https://cloud.githubusercontent.com/assets/16850445/12563047/82bb157c-c3a8-11e5-912e-e8431bc6d094.JPG)

next step , only one "/" 

![unbenannt5](https://cloud.githubusercontent.com/assets/16850445/12563542/0dd752e0-c3ab-11e5-9d46-d62e909be917.JPG)


the same

![unbenannt6](https://cloud.githubusercontent.com/assets/16850445/12563416/88cb08a8-c3aa-11e5-94bd-bd9a1053b94f.JPG)

**Comment by Dobi29** [comment] 2016-01-25 20:35
log-file

[0] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motioneye/motion.conf
[0] [NTC] [ALL] config_thread: Processing config file thread-1.conf
[0] [NTC] [ALL] config_thread: Processing config file thread-3.conf
[0] [NTC] [ALL] config_thread: Processing config file thread-2.conf
[0] [ALR] [ALL] conf_cmdparse: Unknown config option "rtsp_uses_tcp"
[0] [NTC] [ALL] motion_startup: Motion 3.2.12+git20140228 Started
[0] [NTC] [ALL] motion_startup: Logging to syslog
[0] [NTC] [ALL] motion_startup: Using default log type (ALL)
[0] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31:554/ucast/11)
[3] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31:554/ucast/11)
[3] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
[3] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31:554/ucast/11)
[3] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31:554/ucast/11)
[2] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[2] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[2] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[2] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[2] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[3] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.178.31:554/ucast/11)
[3] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.178.31:554/ucast/11)
[2] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[2] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD

**Comment by Dobi29** [comment] 2016-01-28 17:22
i made a second installion with motioneyeos and there i can get the cam with rtsp://ipadresse:554/ucast/11

**Comment by ccrisan** [comment] 2016-01-29 08:21
Most likely you weren't using motion-mrdave. I'll close the issue now.

**Closed by ccrisan** 2016-01-29 08:21 UTC

**Comment by DrCord** [comment] 2016-09-11 00:01
I am still getting this problem with a Wansview 720P network camera. It works perfectly fine via VLC and through Onvif device manager with the url: rtsp://192.168.1.113:554/live/ch0 but shows the grey screen as show via the above screenshots...

**Comment by DrCord** [comment] 2016-09-12 14:24
This was caused by using a "+" in the password for the camera, apparently that character cannot be sent correctly in the authentication phase from motioneye...?

**Comment by blindrain** [comment] 2018-06-22 15:20
I have this problem on x86 and x64 ubuntu systems  following your directions to install motioneye on these systems .  I get 401 unauthorised errors in the logs but if I use straight ffmpeg to record the video from these systems I'm able to record the video.    this is an rtsp feed. and I have no special characters in my password.

**Comment by blindrain** [comment] 2018-06-23 19:19
how do I use ffmpeg to restream this so it works in motion eye. 

 ffmpeg -i rtsp://username:password@10.24.23.15:80/videoMain -acodec copy -vcodec copy -f h264 udp://0.0.0.0:1234/videoMain

Doesn't seem to work.
