### ISSUE TITLE
motion recording not working on rpi3

### ISSUE THREAD

**Issue by eiri1234** [ccrisan/motioneye#225] opened 2016-06-13 17:32 UTC
this is the 3rd installation i have tried to no avail on my rpi3, motion eye will not record anything. If anyone can help would much appreciate, Thank You in advance.

**Comment by ccrisan** [comment] 2016-06-13 19:39
Can you send me your config files (motion.conf, thread-*.conf)? Please make sure to remove passwords and other sensitive data from them. Also, what version of motionEye do you run?

**Comment by eiri1234** [comment] 2016-06-13 20:37
Thank you for answering  me so fast calin, I really appreciate your work so
much. For the rpi1 and 2 the settings for video and still images are by
default turned on but for rpi3 it is not and all I had to do is switch to
on for both. Thanks for your email and all your work.

**Comment by ccrisan** [comment] 2016-06-14 08:12
So the problem is gone then? Can we close the issue?

**Comment by eiri1234** [comment] 2016-06-14 10:23
Yes all done thanks.

**Closed** 2016-06-14 11:17 UTC
