### ISSUE TITLE
motioneye service fails to start

### ISSUE THREAD

**Issue by cferrall** [ccrisan/motioneye#141] opened 2016-03-04 04:05 UTC
I installed motioneyeos on a RaspberryPi and everything was great.  Last night the service stopped and now the service will not start.  It hangs on "starting motioneye" for about two minutes and restarts the board.  It also has an error that the file system couldn't mount when the board first powers up.  It was working last night, this morning it was in this cycle.  Prior to the board rebooting the devices address is shown on the screen.  I do have SSH access, except for a few second after the board reboots..

Any suggestions?

**Comment by ccrisan** [comment] 2016-03-04 07:33
What OS version do you use? If you have SSH for a minute or so, please log in and do a `cat /var/log/motioneye.log` to see what the problem is. My bet is that you have removed some media files and the `/data/output` directory got removed as well (a bug that I recently fixed).

**Comment by cferrall** [comment] 2016-03-04 12:49
Thanks for the quick reply.   I'll check the version but it was up to date
Wednesday night.  I am able to mount the SD card if connected to another
machine.  What directory would be missing?  I did enable motion recording
the night this occurred.  One of the last things I did was delete the
recordings.

Chris

**Comment by ccrisan** [comment] 2016-03-04 16:03
The /data is the local mount point. Check for the `/output` folder in the root of the third partition's filesystem. It's probably gone anyway. Just create it and you'll be able to boot the OS again.

**Comment by cferrall** [comment] 2016-03-04 21:39
Sweet.

Thanks

**Comment by ccrisan** [comment] 2016-03-05 15:22
I'll close the issue now, as the root cause has been identified and fixed.

**Closed by ccrisan** 2016-03-05 15:22 UTC
